"""
Japanese Magpie SFT dataset (llm-jp/magpie-sft-v1.0).
https://huggingface.co/datasets/llm-jp/magpie-sft-v1.0

High-quality Japanese single-turn instruction-following data generated by the
Magpie method (cyberagent/calm3-22b-chat as user, Qwen2.5-32B-Instruct as assistant).
~132K examples. Higher quality than izumi-lab/llm-japanese-dataset.

Field: conversations (list of {"role": "user"/"assistant", "content": "..."})
"""

from datasets import load_dataset
from tasks.common import Task


class MagpieJa(Task):
    """
    Japanese Magpie SFT. ~132K single-turn instruction-output pairs.
    """

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.ds = load_dataset("llm-jp/magpie-sft-v1.0", split="train").shuffle(seed=42)

    @property
    def eval_type(self):
        return 'generative'

    def num_examples(self):
        return len(self.ds)

    def get_example(self, index):
        row = self.ds[index]
        messages = [
            {"role": msg["role"], "content": msg["content"]}
            for msg in row["conversations"]
            if msg["role"] in ("user", "assistant")
        ]
        if not messages or messages[0]["role"] != "user":
            messages = [
                {"role": "user",      "content": "こんにちは"},
                {"role": "assistant", "content": "こんにちは！何かお手伝いできることはありますか？"},
            ]
        return {"messages": messages}
